include: package:flutter_lints/flutter.yaml

analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamics: false

linter:
  rules:
    # - prefer_const_constructions
    # - prefer_const_declarations
    # - avoid_print
    # - use_key_in_widget_constructions
    # - always_use_package_imports